### ISSUE TITLE
Remake for Solidity.

### ISSUE THREAD

**Issue by androlo** [eris-ltd/lllc-server#33]
We need a new LLLC server for Solidity. The new server doesn't have to be more then a simple (but proper server) for solc. Maybe there is one already, somewhere, otherwise I'd (again) suggest writing it in C++ because there's no good reason not to. The server is tiny, and it would get access to libsolidity (and all the other compilers) rather then running os.Exec in Go and parse stdout like it does now. The legacy compiler would still continue to run of course.

These are some things that should be done.

1) We don't need more then an RPC endpoint imo, and only http, but It should implement JSON-RPC properly. We say it does in README, but it does not.

2) The calling process can be improved by a lot. All you need to run the compiler is a list of files. From what I understand, calling the server requires a bunch of folder and files to be created on the local machine? If that's the case, then that can be gotten rid of. The calling clients only need to pass a parameters object that looks something like this:

```
[{"filename": name, "source": source}, {"filename2": name, "source2": source}, ...]
```

Flags and such could also be included, and the language field (if it needs to support lll/serpent).

3) Not really high priority, but we should expose more methods later such as opcodes, ast, asm, and natspec, and optimization flags etc.

4) Bloat should be reduced. If I'm not mistaken it builds the entire cpp-ethereum library (including the GUIs), and pulls in half of the go stack for the server. A majority of this could be cut out.

I would do this.

**Comment by compleatang** [comment]
This is good. I'm happy with this. As you said, though, it's pretty low priority. 

The point where I disagree here is in having the compilers be solidity only. I'm not sure we gain a benefit from being this opinionated. 

We should continue to maintain an overall compilers server which is a single container for all the languages, but I guess we could just build the server to support that with a language switch even if in cpp in process. 

Alternatively we can just leave the current go server as a switch with reverse proxy for solidity compilation. 

Let's revisit this end of July or so.

**Comment by ebuchman** [comment]
I knew this day would come.  lllc-server only depends on folders for the sake of caching. Also there was a time when "only make solidity" wasn't a build option. Since the solc cli offers a bunch more features it would probably make sense to have something devoted to it directly and calling the cpp library, and ideally only it so the image doesn't have to be massive. the current server also doesnt handle multiple contracts properly since its used to one contract at a time. we'll also still probably want to handle solidity includes/creates recursively, which is what most of the lllc-server code was doing. so maybe we'll just keep a golang client for it that handles that part, and wrap the cli itself in a little cpp http.

**Comment by androlo** [comment]
I agree, this is not highest priority. From middle-layer PoV it doesn't need much else then what's already there. Whether it calls libsolidity or solc (through os.exec) is not important. Also, I rarely see people using import, or even know that it exists, so also not a rush, but I guess we've kind of of neglected this library. It should be updated at some point.

The solidity compiler imports doesn't really need massaging like the other ones did. It supports multiple source files. For example, if I have many files that needs compiling, some importing from others, then all i do is compile as usual but pass them all to the compiler. `solc --binary stdout file1.sol file2.sol ...`. It doesn't matter in which order they're passed. Same syntax for all commands, just different command names, so it'll be easy to use the same method for everything. The request params would only need to be a set of (filename - filedata) pairs, the command name and some optimization flags and stuff.

Also I think we should definitely compress before sending.

**Comment by androlo** [comment]
I'm starting to think this will not be enough for long, but will require a lot of patching. The way I normally work with Solidity contracts now is by setting up a proper workspace with sub folders and external dependencies etc. Solc still needs a few things, like adding the -o flag to set an output dir (there's a pt story for that), but other then that it basically supports a normal code-project setup at this point.

If we're gonna support remote compiling beyond passing in one file, I think the best way would perhaps  be to have the client compress the entire workspace and send it along with the build instructions. The server would unpack it into a temporary folder (like now), build, then zip up the build folder and return it. A clever build system (like the gulp-based one I am working on for myself) can use a flag to just swap out the solc build command with the call to the server, unpack the files into the local build folder and continue on from there with any post build stuff - as if the build was done locally.

This will gradually get more advanced. There will be lots of maintenance work to support these type of setups. I think we should decide if we want the simple system for onboarding or an advanced one.

**Comment by ebuchman** [comment]
whats the simple system?

**Comment by androlo** [comment]
the current one.

**Comment by androlo** [comment]
so no real modifications needed. pass a file, get the source and abi.

**Comment by androlo** [comment]
or a bunch of them i guess. either way, no need to go all out with the workspaces and build instructions etc. that will actually be dangerous too as people could pass in mega files and compile ast files that are gigabytes in size etc. Guess that's dangerous now too, in a way.

**Comment by androlo** [comment]
basically crash the server.

**Comment by compleatang** [comment]
done. will need to be massaged, but we have a good start. let's deprecate in favor of more precise issues as things arise.
